# Fast linker configuration for Bevy
# This uses the system's default linker which is usually fast enough

# Linux
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-Clink-arg=-fuse-ld=lld"]

[target.aarch64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-Clink-arg=-fuse-ld=lld"]

# Windows
[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"

[target.x86_64-pc-windows-gnu]
linker = "rust-lld.exe"

[target.aarch64-pc-windows-msvc]
linker = "rust-lld.exe"

# macOS - use system linker (already fast)
[target.x86_64-apple-darwin]
rustflags = [
  "-C", "link-arg=-fuse-ld=/usr/bin/ld"
]

[target.aarch64-apple-darwin]
rustflags = [
  "-C", "link-arg=-fuse-ld=/usr/bin/ld"
]